[show_info]
year = 2022
show_type = "Standard" #Valid types are Standard, Mutation, Combined or Standard/Mutation
date = "Feb 2nd"
start_time = "8am"
end_time = "6pm"


[branch_info]
branch_name = "Colorado Branch"